tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "error": "#ffb4ab",
              "on-tertiary-container": "#480063",
              "on-surface": "#e4e1e9",
              "inverse-surface": "#e4e1e9",
              "surface-dim": "#131318",
              "primary-container": "#568dff",
              "on-secondary-fixed": "#002021",
              "surface": "#131318",
              "tertiary-container": "#d05bff",
              "secondary-container": "#00f4fe",
              "surface-variant": "#35343a",
              "on-error-container": "#ffdad6",
              "surface-container": "#1f1f25",
              "secondary-fixed": "#63f7ff",
              "tertiary-fixed-dim": "#ecb1ff",
              "on-background": "#e4e1e9",
              "surface-tint": "#b0c6ff",
              "primary-fixed": "#d9e2ff",
              "tertiary-fixed": "#f9d8ff",
              "inverse-primary": "#0058cb",
              "on-primary-fixed-variant": "#00429c",
              "on-primary-fixed": "#001945",
              "error-container": "#93000a",
              "surface-bright": "#39383e",
              "on-secondary": "#003739",
              "secondary-fixed-dim": "#00dce5",
              "inverse-on-surface": "#303036",
              "on-tertiary-fixed-variant": "#75009e",
              "on-tertiary": "#520070",
              "surface-container-high": "#2a292f",
              "on-error": "#690005",
              "on-primary-container": "#002661",
              "surface-container-lowest": "#0e0e13",
              "tertiary": "#ecb1ff",
              "secondary": "#e6feff",
              "outline-variant": "#424655",
              "surface-container-highest": "#35343a",
              "background": "#131318",
              "primary": "#b0c6ff",
              "on-secondary-container": "#006c71",
              "on-tertiary-fixed": "#320046",
              "primary-fixed-dim": "#b0c6ff",
              "outline": "#8c90a1",
              "on-secondary-fixed-variant": "#004f53",
              "on-primary": "#002d6f",
              "surface-container-low": "#1b1b20",
              "on-surface-variant": "#c2c6d8"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "margin-mobile": "20px",
              "margin-desktop": "64px",
              "gutter": "24px",
              "container-max": "1280px",
              "base": "8px"
      },
      "fontFamily": {
              "headline-md": ["Sora"],
              "display-lg": ["Anton", "Sora"],
              "headline-lg-mobile": ["Anton", "Sora"],
              "body-md": ["Hanken Grotesk"],
              "label-md": ["Montserrat", "sans-serif"],
              "body-lg": ["Hanken Grotesk"],
              "display-lg-mobile": ["Anton", "Sora"],
              "headline-lg": ["Anton", "Sora"]
      },
      "fontSize": {
              "headline-md": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
              "display-lg": ["72px", {"lineHeight": "80px", "letterSpacing": "0.02em", "fontWeight": "400"}],
              "headline-lg-mobile": ["32px", {"lineHeight": "38px", "letterSpacing": "0.01em", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "24px", "fontWeight": "400"}],
              "label-md": ["14px", {"lineHeight": "20px", "letterSpacing": "0.02em", "fontWeight": "600"}],
              "body-lg": ["18px", {"lineHeight": "28px", "fontWeight": "400"}],
              "fontSize-headline-lg": ["40px", {"lineHeight": "48px", "letterSpacing": "0.01em", "fontWeight": "400"}]
      }
    },
  },
}
